### ISSUE TITLE
Cucumber dependency

### ISSUE THREAD

**Issue by evasconcelos** [testomatio/check-cucumber#37]
Shouldnt `cucumber` be replaced with `@cucumber/cucumber` ?

as per https://www.npmjs.com/package/cucumber : 

> This package has been deprecated
> Author message:
> 
> Cucumber is publishing new releases under @cucumber/cucumber

**Comment by DavertMik** [comment]
Thanks, sure, it should!

**Comment by olexandr13** [comment]
https://github.com/testomatio/check-cucumber/pull/53

cucumber was updated from version 6.x to 9.x. thus requires precise testing. Something could be broken.


@TetianaKhomenko Testing details:
you have to install `check-cucumber@beta` (0.5.16) version to test.

**Comment by olexandr13** [comment]
Fixed in 0.5.17
