### ISSUE TITLE
Check-cucumber seems to duplicate tests after changing structure in Testomat

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/check-cucumber#63]
when changing the structure in code the old tests are kept in Testomat

this is the command used
`npx check-cucumber@latest "**/*.feature" --dir features/test --sync --keep-structure --no-detached`

**To reproduce:**

1. have structure in code
```
features
|__ a.feature
```

2. then sync `npx check-cucumber@latest "**/*.feature" --dir features/test --sync --keep-structure --no-detached`

3. then we move a.feature under a new folder

```
features
|__ featuresA
|____ a.feature
```

4. in testomat we will have

```
features
|__a.feature
|__ featuresA
|____ a.feature
```

**Comment by aakrem** [comment]
also `--update-ids` won't help much as it will insert not needed data in our features.
So I think we need a sort of --overwrite or so, that will take always what's defined in definitions source code.

**Comment by olexandr13** [comment]
Structure is changed if IDs are present

![Image](https://github.com/user-attachments/assets/148b42fc-8f59-42d3-97aa-c37af2af0b82)

Please give exact example if adding IDs does not help for you, cause I can't reproduce with the example below
